### ISSUE TITLE
MultiLevelPointer problem

### ISSUE THREAD

**Issue by Ezriral** [pinwhell/Emulator-Android-External-Memory-Hacking#2]
Im really happy that i found your project, and i like to use it, but i am stucking at some problem i cannot really figure out how to solve it.
I found the pointer for the value in cheatengine.

```
    uintptr_t libil2cppAddr = p.GetModBaseAddr("libil2cpp.so.2");
    uintptr_t pointAddr = p.FindDMAddy(libil2cppAddr + 0x0014ED90, {0x8CC, 0x830, 0x154, 0x2C, 0x8, 0x184, 0x408});
    int value = p.ReadProcessMemory<int>(pointAddr);

```

the problem is its not solving the way to the pointer correctly. 
Here you can see the correct CE way.
![CE](https://user-images.githubusercontent.com/56836301/170778034-075f6797-e64f-4ef4-b4bc-fe5f2c23552f.JPG)

but over the program its showing different addresses and i have the feeling its also dont find the ModBaseAddress.
In the follwing image you can see the path of the address which is calculated by your function "uintptr_t ProcessManager::FindDMAddy(uintptr_t base, std::vector<uintptr_t> offsets)" i added some lines to show me what the output is for every iteration.
```
uintptr_t ProcessManager::FindDMAddy(uintptr_t base, std::vector<uintptr_t> offsets)
{
    uintptr_t result = base;

    char hex_string[20];
    int f = reinterpret_cast<std::uintptr_t>(result);
    sprintf(hex_string, "%X", f); //convert number to hex
    printf("Result FindDMAddy: %s \n", hex_string);

    for(int i = 0; i < offsets.size(); i++)
    {
	f = reinterpret_cast<std::uintptr_t>(result);
	sprintf(hex_string, "%X", f); //convert number to hex
	printf("Result Loop FindDMAddy: %s \n", hex_string);

        result = ReadProcessMemory<uintptr_t>(result);
        result += offsets[i];

	printf("Offset Int: %u", offsets[i]);
	f = reinterpret_cast<std::uintptr_t>(offsets[i]);
	sprintf(hex_string, "%X", f); //convert number to hex
	printf(" => Hex %s \n", hex_string);
    }

    return result;
}
```

![NA](https://user-images.githubusercontent.com/56836301/170778360-7cb3be34-b426-4682-9083-f8c3bff28e46.JPG)

So yes, i would be happy if you could tell me whats wrong here, cause i also dont know right now where to post my question. And i guess asking the dev would be the right decesion.

Thank you

**Comment by pinwhell** [comment]
im happy you found usefull my project, have you checked "libil2cppAddr"? can you try libil2cpp.so?, also, where are you running this, in a emulator or real device, witch device or emulator

**Comment by Ezriral** [comment]
Im sorry im using MEmu 7.6.6 Android 7.1.2 and yes its a emualtor.

And yes i also changed it to libil2cpp.so before but both are not working,
![NA2](https://user-images.githubusercontent.com/56836301/170780779-77ae4940-de75-47fc-bebc-df2ba0da71fd.JPG)

**Comment by pinwhell** [comment]
its probably a parsing error, located in the function ParseMapLineSegment , can you send me samples of the maps of the process your trying to access?

**Comment by Ezriral** [comment]
I hope this is what you need
[map.txt](https://github.com/Mst1k/Emulator-Android-External-Memory-Hacking/files/8789546/map.txt)
.

**Comment by pinwhell** [comment]
the parser seems working on this samples properly, need to watch GetMapsBuffer clousely to see if it retrieve the full maps file

**Comment by Ezriral** [comment]
Yes i alreday checked it and wanna post it right now. it seems like the libi2lcpp.so.2 doesnt exist in the map. I can find the 
line 
`lib/arm/libil2cpp.so`
but i cannot find the selected one from CE

Here one with the standard il2cpp and the other one with "so.2"
![NA2](https://user-images.githubusercontent.com/56836301/170787327-2da34f2e-dc26-4cfc-9606-4f50ad4902ac.JPG)
![NA3](https://user-images.githubusercontent.com/56836301/170787353-cea1bf8f-ccee-416f-b6a0-27f0cc0e4827.JPG)

**Comment by pinwhell** [comment]
134217728 -> 0x8000000, witch is correct, 08000000-0b2ca000 r--p 00000000 08:13 294959     /data/app/com.******.*******-2/lib/arm/libil2cpp.so, so what about finddmaddy, still having same issue?

**Comment by Ezriral** [comment]
if im right, im trying to open libil2cpp.so.2 which doesnt exist in the map so its address is zero. And if im open libil2cpp.so it doesnt point to the correct address
![NA2](https://user-images.githubusercontent.com/56836301/170788929-a02a0d76-84f7-49f6-b2ea-7ac5935921f8.JPG)
![NA3](https://user-images.githubusercontent.com/56836301/170788938-4f5a1a4a-67ce-4c2c-8b74-979347958081.JPG)
.

**Comment by pinwhell** [comment]
probably cheat engine gives another name to the librarys(which i didnt see before), to check if libil2cpp.so.2 == libil2cpp.so(in maps), just compare both addresses in memory, if both are 0x08000000, then dont worry about the naming and try using it like that in the lib!

**Comment by Ezriral** [comment]
Okay i hope i will find a solution, thank you for helping a stranger : ) have a nice day sir.

**Comment by pinwhell** [comment]
no problem!, hope it helped, anything else we are here to help!
