### ISSUE TITLE
We need your help 

### ISSUE THREAD

**Issue by SaSukiTB** [pinwhell/Emulator-Android-External-Memory-Hacking#5]
.

**Comment by pinwhell** [comment]
I am not available for now i apreciated you guys invited me

**Comment by SaSukiTB** [comment]
ok no problem when we can talk ?
One more thing i saw in your video Android EntityList Loop External Demo, that you are using cheat engine on bluestacks, how is that possible you can find libil2cpp.so, can you explain please we are working on an external cheat for the first time.
Sorry about my english, its not my main language.

**Comment by pinwhell** [comment]
@PinwhellGT telegram

**Comment by SaSukiTB** [comment]
hey brudda i lost your telegram after i format my pc, send me your telegram, @SaSukiG
